
name: compile_examples_iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        xcodebuild-workspace: |
          ['coresdk-integrations/coresdk-ios/FleksyCoreSample.xcodeproj']
        xcodebuild-scheme: |
          ['FleksyCoreSample']
        
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and archive ${{ matrix.xcodebuild-scheme }}
        working-directory: ./${{ matrix.xcodebuild-workspace }}
        run: |
          xcodebuild 
            -resolvePackageDependencies 
            -workspace project.xcworkspace 
            -scheme ${{ matrix.xcodebuild-scheme }} build 
            -configuration Release archive 
            -archivePath $PWD/build/${{ matrix.xcodebuild-scheme }}.xcarchive
            
      - name: Create simulator app
        run: |
          cd ios && xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/${{ matrix.xcodebuild-scheme }}.xcarchive \
            -exportOptionsPlist $PWD/ci.plist \
            -exportPath $PWD/build
